#!/bin/bash
# vim: set ft=sh

set -e

payload=$TMPDIR/git-branch-heads-resource-request

cat > $payload <&0

jq \
  '. * {
    source: {
      branch: .version.branch
    }
  } + {
    version: {
      ref: .version.ref
    }
  }' < $payload |
  ${GIT_RESOURCE_IN:-/opt/git-resource/in} "$@" |
  jq --slurpfile payload $payload \
    '. + {version: ($payload | .[0].version)}'

cd "$@"
mkdir .git/git-branch-heads-resource
jq < $payload -r .version.branch > .git/git-branch-heads-resource/branch
